// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTS4rdSCLGe8MYgsUKK77fTsVOpcDSK5g',
    appId: '1:929614850850:web:796713af7c3317790b537b',
    messagingSenderId: '929614850850',
    projectId: 'flutter-app-distribution-2b965',
    authDomain: 'flutter-app-distribution-2b965.firebaseapp.com',
    storageBucket: 'flutter-app-distribution-2b965.firebasestorage.app',
    measurementId: 'G-4LG1441FB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUjm4TRRTHuHOH2L7g23jab7eBqnyz1eo',
    appId: '1:929614850850:android:a87e50722b884a7e0b537b',
    messagingSenderId: '929614850850',
    projectId: 'flutter-app-distribution-2b965',
    storageBucket: 'flutter-app-distribution-2b965.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhfFPqsVCsNdu_9Y_yLNb7OH-H6Nhj9co',
    appId: '1:929614850850:ios:91b0feafcc544a490b537b',
    messagingSenderId: '929614850850',
    projectId: 'flutter-app-distribution-2b965',
    storageBucket: 'flutter-app-distribution-2b965.firebasestorage.app',
    iosBundleId: 'com.example.doctorReservationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhfFPqsVCsNdu_9Y_yLNb7OH-H6Nhj9co',
    appId: '1:929614850850:ios:91b0feafcc544a490b537b',
    messagingSenderId: '929614850850',
    projectId: 'flutter-app-distribution-2b965',
    storageBucket: 'flutter-app-distribution-2b965.firebasestorage.app',
    iosBundleId: 'com.example.doctorReservationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTS4rdSCLGe8MYgsUKK77fTsVOpcDSK5g',
    appId: '1:929614850850:web:23c0b38a0669477f0b537b',
    messagingSenderId: '929614850850',
    projectId: 'flutter-app-distribution-2b965',
    authDomain: 'flutter-app-distribution-2b965.firebaseapp.com',
    storageBucket: 'flutter-app-distribution-2b965.firebasestorage.app',
    measurementId: 'G-S0NV7PK533',
  );
}
