default_platform(:android)

platform :android do
  desc "Lane For Android Firebase App Distribution"
  lane :firebase_distribution do
   sh"flutter clean"
   sh "flutter build apk --release --flavor prod --target lib/main_prod.dart --no-tree-shake-icons"
   firebase_app_distribution(
    app: "1:929614850850:android:a87e50722b884a7e0b537b",
    firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
    android_artifact_type:"APK",
    android_artifact_path:"../build/app/outputs/flutter-apk/app-prod-release.apk",
    testers:"mohamedmedo9932@gmail.com, mohammed.ossama@instashop.ae",
    release_notes:"Handled API error model and finished home screen UI&Logic",
    upload_timeout: 600
  )
  end
end
